name: Install Android SDK

on:
  push:
    branches:
      - main

jobs:
  setup-android-sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: install dependencies
        run: npm i

      - name: run test
        run: npm run android.app.cucumber
        
      
