name: Install Android SDK

on:
  push:
    branches:
      - main

jobs:
  setup-android-sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/android-sdk
          rm cmdline-tools.zip

      - name: Configure Android SDK
        run: |
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-30" "build-tools;30.0.3"

      - name: Set up environment variables
        run: echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV

      - name: Verify Android SDK installation
        run: |
          echo "Android SDK installed:"
          $HOME/android-sdk/platform-tools/adb --version
          $HOME/android-sdk/cmdline-tools/bin/sdkmanager --list
