name: Run Android App Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip commandlinetools-linux-8512546_latest.zip
        yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
        $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-30" "build-tools;30.0.3" "system-images;android-30;google_apis;x86"

    - name: Set up Android Emulator
      run: |
        echo no | $HOME/android-sdk/cmdline-tools/bin/avdmanager create avd -n test -k "system-images;android-30;google_apis;x86"
        $HOME/android-sdk/emulator/emulator -avd test -no-window -no-audio &

    - name: Wait for Emulator to Boot
      run: |
        adb wait-for-device
        adb shell input keyevent 82

    - name: Run Android App Cucumber Tests
      run: |
        npm install
        npm run android.app.cucumber
