name: Install Android SDK

on:
  push:
    branches:
      - main

jobs:
  setup-android-sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
         node-version: '16'
        
      - name: Install dependencies
        run: |
          npm install -g appium
          npm install

      - name: Start Appium Server
        run: |
           appium &

      - name: Set up Android Emulator
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip -d $HOME/android-sdk
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/bin/sdkmanager "platforms;android-30" "system-images;android-30;google_apis;x86"
          echo no | $HOME/android-sdk/cmdline-tools/bin/avdmanager create avd -n test -k "system-images;android-30;google_apis;x86" --force
          emulator -avd test -no-skin -no-audio -no-boot-anim -verbose &

      - name: run test
        run: npm run android.app.cucumber
        
      
