name: Run Appium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O android-commandlinetools.zip
        unzip android-commandlinetools.zip -d $ANDROID_HOME/cmdline-tools
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin

    - name: Accept licenses
      run: yes | sdkmanager --licenses

    - name: Download system image and create AVD
      run: |
        echo 'y' | sdkmanager --install "system-images;android-30;google_apis;x86"
        echo 'no' | avdmanager create avd -n "emulator-30" -d "pixel" -k "system-images;android-30;google_apis;x86" -c 128M -f

    - name: Configure AVD
      run: |
        printf 'hw.keyboard = yes\nhw.ramSize = 1024\n' >> ~/.android/avd/emulator-30.avd/config.ini

    - name: Start emulator
      run: |
        nohup emulator -avd "emulator-30" -no-snapshot -no-boot-anim -no-audio -no-window -delay-adb >/dev/null 2>&1 &

    - name: Wait for emulator to start
      run: sleep 60

    - name: Print emulator version
      run: emulator -version

    - name: Print running devices
      run: adb devices

    - name: Run Appium Tests
      run: |
        # Ensure the emulator is fully booted
        adb wait-for-device
        adb shell 'while [[ "$(getprop sys.boot_completed)" != "1" || "$(getprop init.svc.bootanim)" != "stopped" ]]; do sleep 1; done;'
        adb shell 'svc power stayon true'
        adb shell 'settings put global window_animation_scale 0'
        adb shell 'settings put global transition_animation_scale 0'
        adb shell 'settings put global animator_duration_scale 0'
        adb shell 'settings put secure long_press_timeout 1500'
        adb shell 'settings put secure show_ime_with_hard_keyboard 0'
        adb shell 'settings put secure spell_checker_enabled 0'
        adb shell 'settings put secure autofill_service null'
        adb shell input keyevent 82
        # Run your Appium tests here
        # e.g., `npm test` or `mvn test` or any other command to execute your tests

    - name: Clean up
      run: |
        adb emu kill
